### PR TITLE
Create npmpublish.yml GitHub Action

### PR DESCRIPTION
**Pull request by miguel-a-calles-mba**
## What did you implement:

Closes #XXXXX

Adding a GitHub Action to automatically publish to npm.

## How did you implement it:

Added a GitHub Action YAML workflow.

## How can we verify it:

Define the `NPM_TOKEN` secret in the settings. Update the package version, create a release, and see the action work. https://github.com/serverless-heaven/serverless-webpack/actions

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by miguel-a-calles-mba** [comment]
@HyperBrain Are you comfortable creating a npm token and adding it to the "secrets" in this repository's settings? This way we can automatically publish to npm when we create a GitHub release.

**Comment by revgum** [comment]
Thank you @HyperBrain and @miguel-a-calles-mba for keeping traction on this repo, it's very handy and still quite active! 

I'm eagerly awaiting PR #570 as I'm sure there are several others as well.

**Comment by miguel-a-calles-mba** [comment]
@revgum np.

I'm looking forward to other PRs too. =)

**Comment by HyperBrain** [comment]
@Miguel Calles <miguelacallesmba@gmail.com>  I will create a npm token and
let you know.

**Comment by miguel-a-calles-mba** [comment]
Thanks @HyperBrain !

**Comment by miguel-a-calles-mba** [comment]
@HyperBrain @jamesmbourne @rdsedmundo Reference the internal team discussion about the updated npm token secret.

**Pull request merged**
