### PR TITLE
New: Use woker-farm to handle webpack multi compile

### LINKED ISSUE #299: JavaScript heap out of memory
# This is a Bug Report

## Description

I'm in the process of trying to upgrade `serverless-webpack` version from `2.2.3`, where I do not experience the following issue. Our serverless configuration has `package: invididually: true` set, and about 40 functions. When I try to upgrade to a later version of `serverless-webpack` and run `sls webpack`, the build will run for about a minute and then I get the following error:

```
lambda:daniel.cottone $ npm run build

> expert-api-lambda@0.1.0 build /Users/daniel.cottone/Projects/expert-api/lambda
> sls webpack --stage dev

Serverless: Bundling with Webpack...
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json

<--- Last few GCs --->

[42611:0x104001600]    55964 ms: Mark-sweep 1405.7 (1508.8) -> 1405.7 (1508.8) MB, 1721.0 / 0.0 ms  allocation failure GC in old space requested
[42611:0x104001600]    57889 ms: Mark-sweep 1405.7 (1508.8) -> 1405.5 (1487.3) MB, 1923.4 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1923 ms) last resort 
[42611:0x104001600]    59801 ms: Mark-sweep 1405.5 (1487.3) -> 1405.4 (1486.8) MB, 1903.6 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x37341f01ba79 <JS Object>
    1: set [native collection.js:~247] [pc=0x29d828934f21](this=0x332730f95301 <a Map with map 0x23d2df14319>,p=0x3dd499abec41 <String[11]: MediaSource>,x=0x2589b9b1c819 <a SymbolObject with map 0x399abfecde11>)
    2: /* anonymous */(aka /* anonymous */) [/Users/daniel.cottone/Projects/expert-api/lambda/node_modules/typescript/lib/typescript.js:~23166] [pc=0x29d828ba5830](this=0x37341f002241 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::Rehash(v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/local/bin/node]
 8: v8::internal::Runtime_MapGrow(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0x29d827e840bd
10: 0x29d828934f21
11: 0x29d828ba5830
12: 0x29d827e86bbb
13: 0x29d828f85beb
Abort trap: 6
```

If I change my serverless config to not package individually, `package: individually: false` then this error goes away. I have tested this with version `3.0.0` and the latest, `4.1.0` with the same results. Don't have this issue with `2.2.3`.

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.1.0
* ***Webpack version you're using***: 3.10.0
* ***Serverless Framework Version you're using***: 1.24.0
* ***Operating System***: macOS 10.12.6
* ***Stack Trace (if available)***: see above

### PR DESCRIPTION
**Pull request by soda0289**
## What did you implement:

Memory usage of this plugin is really high when using package individually. This is because we store the webpack stats/results from each function compile until all functions are finished compiling. These stats object contain all of the compiled source code for each module and chunk generated. We don't use many properties from webpack stats and this change adds a new function ` processWebpackStats()` that only extracts the properties we need (cliOutput, errors, outputPath, and externalModules). This greatly reduces the memory footprint during compile and lets the garbage collector clean up a lot more memory.

Lowering the memory improves performance a little bit but there's still a chance of a memory leak if you are using many webpack plugins that do not cleanup properly. To fix this we must ensure memory is cleaned up after every function compile. To do this I added the npm package `worker-farm` that runs each function compile in a separate thread/process. This way we can end the process and clean up the memory after each compilation is done. This also lets us compile multiple functions at once and has a huge performance improvement. Almost 50% faster in some repositories I have tested this on. This is the same pattern that `parallel-webpack` uses to improve performance of webpack multi compile. 

Closes #299 

## How did you implement it:

Refactored the code to create 2 different compilers. Single compiler that uses webpack() in main thread, same as current implementation. Multi compiler uses `worker-farm` to run each webpack compilation in a seperate thread. Since each worker is its own process we can only pass in serializable objects into the thread. This means we can pass webpack config file path or a JSON object that does not have functions or other non serializable objects. We use the V8 serialize function to test if a webpack config can be serialized using the HTML structured clone algorithm. This might be a breaking change but I don't think its possible to include a non serializable object into a serverless config. If it is possible it will throw an error letting the user know they should use webpack config file path instead.

## How can we verify it:

 - Enable package individually
 - Run a build or deploy
 - Ensure every function is compiled correclty

## Todos:

- [X] Write tests
- [ ] Write documentation
- [X] Fix linting errors
- [X] Make sure code coverage hasn't dropped
- [X] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by soda0289** [comment]
Its failing since we build on NodeJS 6. V8 serialize function was added in NodeJS 8. I think we should bump up min version to NodeJS10 since 6 has been deprecated for a while. Let me know if that is ok.

**Comment by j0k3r** [comment]
@miguel-a-calles-mba I agree with @soda0289, we should bump minimum version of node to 10.
We should only have build & support for:
- Node 10
- Node 12

AWS disabled ability to update functions running:
- Node.js 6.10 since May 30 2019
- Node.js 8.10 since February 3, 2020

**Comment by miguel-a-calles-mba** [comment]
@HyperBrain, may you please update the Travis CI configuration to test against Node 10 and 12, please? Thanks!

**Comment by j0k3r** [comment]
@miguel-a-calles-mba you can do it on your own by editing `.travis.yml` and `.appveyor.yml`.

**Comment by miguel-a-calles-mba** [comment]
Thanks @j0k3r! I didn't know that.

**Comment by miguel-a-calles-mba** [comment]
@soda0289 May you please merge master into your fork? I'm not able to do it for you. The latest version of master now runs unit tests against Node 8 and 10.

**Comment by miguel-a-calles-mba** [comment]
Nevermind @soda0289. I figured out how to update your PR to update CI node version.

**Comment by miguel-a-calles-mba** [comment]
@soda0289 May you fix the unit tests? I addressed the linting issues, but the test are still failing. Thanks.

**Comment by soda0289** [comment]
@miguel-a-calles-mba Sorry for delayed response. I have fixed up the linting errors and test cases.

Another question I have is if we should add options to allow the user to customize how many threads they want to use or if they want to use multi thread compile at all. Currently it is used every time package individually is set but this might be undesired for some users.

**Comment by soda0289** [comment]
Also should I reabse onto branch 'release/5.4.0' or should I change base branch to be master?

**Comment by miguel-a-calles-mba** [comment]
@soda0289 Maybe there should be a default value of one thread?

We are targeting release/5.4.0.

**Comment by troyready** [comment]
Sane thread default is probably the number of CPU cores (as an example from another ecosystem, I believe that's the default for python's multiprocessing module - using what's returned by `multiprocessing.cpu_count()`)

Having it be configurable would obviously be nice.

**Comment by coyoteecd** [comment]
@soda0289 @miguel-a-calles-mba Any chance to get this fix in? The plugin is becoming nearly unusable for us

**Comment by coyoteecd** [comment]
@soda0289 @miguel-a-calles-mba I did a dry-run of this pull request in our environment and hit an issue.

Previously, the plugin exposed entries and options through slsw.lib.entries and slsw.lib.options. See [code here](https://github.com/soda0289/serverless-webpack/blob/multi-thread-compiler/lib/validate.js#L108-L111) and functional description [here](https://github.com/serverless-heaven/serverless-webpack#full-customization-for-experts). I am using a webpack.config that runs a particular plugin based on a command -line option passed to serverless. Now, slsw.lib.options is undefined, so I can't access those options anymore.

Is there a way to keep the existing functionality, or is there an alternative to get the command line options in the worker thread config?

**Comment by dominics** [comment]
I tried this branch today, and it didn't work out for me. Probably because my webpack config isn't serializable? (It's something like https://gist.github.com/dominics/f9f24430789d1b4c4f0297a31b5b3ff7, so there's a function in there - not a common case.) But there were no errors; the bundled code just didn't have _any_ externals (and the verbose logging just says "no external modules needed")

**Comment by thomaschaaf** [comment]
For us this PR fixed the issue of memory running out :)

**Comment by bryantbiggs** [comment]
will this PR make it into 5.4.0?

**Comment by diogogvhenriques** [comment]
This PR also solves the issue for some of our projects.

**Comment by roni-frantchi** [comment]
This PR had also helped us overcome the OoM errors.  
For us, it worked where #299 which is 5.4, did not.  
We'd love to see this one make it into 5.4

**Comment by bryantbiggs** [comment]
does this mean the change is slated to arrive in `5.4.0`?!

**Comment by j0k3r** [comment]
Sorry I made a mistake while merging `release/5.4.0` into master and removed it. The removal automatically closed that PR. It should now be rebased against the master and fix conflicts.

**Comment by j0k3r** [comment]
@soda0289 could you rebase against the master and fix conflicts? Thanks 🙏

**Comment by mikewolfd** [comment]
@j0k3r What's going on with this? I have a bug that will be fixed by #570

**Comment by Enase** [comment]
@mikewolfd I'm not sure, but looks like it was addressed by https://github.com/serverless-heaven/serverless-webpack/pull/517, see [v5.4.0](https://github.com/serverless-heaven/serverless-webpack/releases/tag/v5.4.0)

**Comment by troyready** [comment]
I'll echo above, from what I can tell this can now be closed. The original issues are now solved for me by using the following serverless config:

```
package:
  individually: true

custom:
  webpack:
    serializedCompile: true
```

**Comment by mikewolfd** [comment]
I upgraded to v5.4.0 but am still getting the problem theoretically fixed by #661, which relied on this PR. If this PR is now irrelevant, I'm not sure where to proceed.

**Pull request closed without merging**
