### PR TITLE
Skip compile & packaging if --no-build is set

### LINKED ISSUE #398: Support --no-build for package` and `deploy
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

When using yarn workspaces, it's common for a service to depend on modules that are contained within the workspace.  In a CI/CD process, we would like to execute a test/build step which produces a deployable artifact (e.g. a zip of the service folder) which can be promoted through various environments.  At deploy time, the deployable artifact will not exist within the 'workspaces' structure, so yarn/npm and thus webpack are unable to locate some of the dependencies.

If `serverless deploy` supported a `--no-build` option, then we could do:

1. `serverless webpack`
1. zip folder
1. unzip in prep for deployment to an environment
1. `serverless deploy --no-build -stage qa` - this should package and deploy the serverless service using the existing `.webpack` contents

* If there is additional config how would it look

N/A

Similar or dependent issue(s):
* https://github.com/serverless/serverless/issues/352 - In reality, this proposal is really only useful due to serverless's deployment model - if this serverless issue were completed, then it would make this option unnecessary, as the output of `serverless package` would then be deployable to any given environment.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.1.5
* ***Webpack version you're using***: 4.8.1
* ***Serverless Framework Version you're using***: 1.27.2
* ***Operating System***: linux
* ***Stack Trace (if available)***: none

### PR DESCRIPTION
**Pull request by jamesmbourne**
## What did you implement:

Closes #398 

Allow the `--no-build` flag to commands that invoke the `before:package:createDeploymentArtifacts` hook. This means that build output can be generated (e.g. in CI environments) and then deployed without having to re-build each time.

## How did you implement it:

Use the existing `build` option to skip the `compile` and `package` steps for the `before:package:createDeploymentArtifacts` hook.

## How can we verify it:

1. Generate build output with `sls webpack`
2. Run `sls deploy --no-build`
3. The existing `.webpack` (or other as specified by `--out`) directory should be used an no Webpack compilation occurs

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by bazaglia** [comment]
@jamesmbourne Amazing PR! I tested it, but got this error when trying to bundle with `sls webpack -r us-east-1`:

```
  TypeError: Cannot read property 'stats' of undefined
      at /Users/andre/my-project/node_modules/serverless-webpack/lib/packExternalModules.js:264:27
```

**Comment by jamesmbourne** [comment]
Hey @bazaglia, thanks for the feedback!

What is the commit hash of `serverless-webpack` you are on? 19031c66c328cf646702cc1c48f490fe2f9a785d should be the most recent on this branch.

Do you have a minimal reproduction of this that you'd be able to share?

**Comment by bazaglia** [comment]
@jamesmbourne I end up using a separate serverless.yml file for deployment that basically imports everything from the original serverless.yml except for the plugins, so I can delete serverless-webpack from my plugin list. In my CI then I can do multi region deployment without this plugin bundling everything again for every single region I deploy to, what takes a lot of time.

But about reproduction steps for your PR, I've just run `sls webpack` and the error was as I pasted above. Nothing much more than that - and I'm sorry I don't have the stack trace anymore. And yes, I've used last commit from your branch.

**Comment by tusamcalles** [comment]
@ceilfors @franciscocpg @hassankhan @HyperBrain @nathanchapman @rdsedmundo Is there a plan to release this PR?

**Comment by rdsedmundo** [comment]
See #563.

**Comment by tusamcalles** [comment]
Thanks @rdsedmundo.

**Comment by bazaglia** [comment]
Oi @rdsedmundo! :)

Apparently this PR is missing a review from you? I've seen many people are looking forward to using this feature. Thanks.

**Comment by rdsedmundo** [comment]
I'll have a look at this and test it by tomorrow EOD, 100%.

**Comment by miguel-a-calles-mba** [comment]
This PR is ready to merge. I have been using it in a production product for weeks.

**Comment by miguel-a-calles-mba** [comment]
@rdsedmundo Please merge this PR if you are satisfied with your test results.

**Comment by RishikeshDarandale** [comment]
@jamesmbourne , Can you please check the package is expected to have all these?

Here is simple example:

```
//serverless.yml
service: multi-comple-config-example

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

custom:
  # webpack config
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: false

provider:
  name: aws
  runtime: nodejs12.x

functions:
  web-app:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
```

```
//server.js
'use strict';

module.exports.handler = function (event, context, cb) {
  cb(null, { message: 'Server Module', event });
}
```

```
//webpack.config.js
const path = require("path");
const slsw = require("serverless-webpack");

module.exports = {
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  entry: {
    server: "./server.js",
  },
  target: "node",
  output: {
    libraryTarget: "commonjs",
    path: path.join(__dirname, ".webpack/web-app"),
    filename: "[name].js",
  },
};
```

```
// package.json
{
  "name": "multi-compile-config",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless": "^1.71.3",
    "serverless-webpack": "^5.3.2",
    "webpack": "^4.43.0"
  }
}
```

> Note: I had checkout locally release/5.4.0 and replaced all files from `lib` directory to `node_modules/serverless-webpack/lib`.

```
// output with release 5.4.0

Archive:  .serverless/multi-comple-config-example.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
     642  Defl:N      618   4% 1980-01-01 00:00 a3921a38  .webpack/web-app/multi-comple-config-example.zip
    1077  Defl:N      510  53% 1980-01-01 00:00 1938c2a5  .webpack/web-app/service/server.js
      77  Defl:N       72   7% 1980-01-01 00:00 eebe0282  client.js
     157  Defl:N      129  18% 1980-01-01 00:00 dbccd4b3  node_modules/.bin/components
     328  Defl:N      219  33% 1980-01-01 00:00 0f9ad637  node_modules/.bin/parser
    1131  Defl:N      546  52% 1980-01-01 00:00 e8632c9a  node_modules/.cache/terser-webpack-plugin/content-v2/sha512/45/17/3ce3a>
    1052  Defl:N      511  51% 1980-01-01 00:00 c9606e6a  node_modules/.cache/terser-webpack-plugin/content-v2/sha512/fd/57/39ff5>
     774  Defl:N      492  36% 1980-01-01 00:00 8a2ecbd0  node_modules/.cache/terser-webpack-plugin/index-v5/22/9b/363b2a229d1909>
     774  Defl:N      494  36% 1980-01-01 00:00 9a1a03c5  node_modules/.cache/terser-webpack-plugin/index-v5/ac/e2/723097fd86f878>
  364736  Defl:N   104652  71% 1980-01-01 00:00 1dbeba55  package-lock.json
     366  Defl:N      225  39% 1980-01-01 00:00 1dcde176  package.json
     122  Defl:N      107  12% 1980-01-01 00:00 8e00dbe4  server.js
     372  Defl:N      229  38% 1980-01-01 00:00 63fb46ee  webpack.config.js
--------          -------  ---                            -------
  371608           108804  71%                            13 files
```

```
// output with 5.3.2
Archive:  .serverless/multi-comple-config-example.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
    1077  Defl:N      510  53% 1980-01-01 00:00 1938c2a5  server.js
--------          -------  ---                            -------
    1077              510  53%                            1 file
```

**Pull request merged**
