### PR TITLE
Fix for multiple config files (when compiling typescript config files)

### LINKED ISSUE #439: Errors when using a Webpack config with multiple configurations
# This is a Bug Report

## Description

I'm using multiples entries in my Webpack config (as described [here](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations)). Everything works fine using `serverless offline start` to develop locally. However, when I try to package it, it fails with the following error:

> TypeError: Cannot read property 'errors' of undefined
    at _.forEach.compileStats (/web-ui/node_modules/serverless-webpack/lib/compile.js:33:40)
    at arrayEach (/web-ui/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/web-ui/node_modules/lodash/lodash.js:9342:14)
    at BbPromise.fromCallback.then.stats (/web-ui/node_modules/serverless-webpack/lib/compile.js:30:11)
    at finalCallback (/web-ui/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/web-ui/node_modules/webpack/lib/MultiCompiler.js:270:6)

According to the code in question in `serverless-webpack/lib/compile.js`, it seems like the variable on line 30 `compileStats` is an array when using multiple configs, rather than an object.

The reason I'm using multiples configurations is that I'm using `serverless-webpack` to build a front-end application written in React that I render server-side using serverless. So one of the configuration is for the client-side, the other configuration is for the server-side. Both are using the same sources, but with different options/loaders, and I want to deploy both of the app together.

I can create a reproduction repo if it can help.

Similar or dependent issue(s):
* #124 
* #102 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.2.0
* ***Webpack version you're using***: 4.17.1
* ***Serverless Framework Version you're using***: 1.30.1
* ***Operating System***: macOS 10.13.6
* ***Stack Trace (if available)***:

> TypeError: Cannot read property 'errors' of undefined
    at _.forEach.compileStats (/web-ui/node_modules/serverless-webpack/lib/compile.js:33:40)
    at arrayEach (/web-ui/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/web-ui/node_modules/lodash/lodash.js:9342:14)
    at BbPromise.fromCallback.then.stats (/web-ui/node_modules/serverless-webpack/lib/compile.js:30:11)
    at finalCallback (/web-ui/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/web-ui/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/web-ui/node_modules/neo-async/async.js:2920:13)
    at runCompilers (/web-ui/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/web-ui/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/web-ui/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/web-ui/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/web-ui/node_modules/webpack/lib/Compiler.js:259:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/web-ui/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/web-ui/node_modules/tapable/lib/Hook.js:35:21)
    at emitRecords.err (/web-ui/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/web-ui/node_modules/webpack/lib/Compiler.js:372:39)
    at emitAssets.err (/web-ui/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/web-ui/node_modules/webpack/lib/Compiler.js:358:14)
    at _err0 (eval at create (/web-ui/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at callback (/web-ui/node_modules/copy-webpack-plugin/dist/index.js:126:17)
    at afterEmit (/web-ui/node_modules/copy-webpack-plugin/dist/index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/web-ui/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/web-ui/node_modules/tapable/lib/Hook.js:35:21)
    at asyncLib.forEach.err (/web-ui/node_modules/webpack/lib/Compiler.js:355:27)
    at done (/web-ui/node_modules/neo-async/async.js:2854:11)
    at /web-ui/node_modules/neo-async/async.js:2805:7
    at /web-ui/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:139:20)
From previous event:
    at ServerlessWebpack.compile (/web-ui/node_modules/serverless-webpack/lib/compile.js:15:8)
From previous event:
    at Object.webpack:compile:compile [as hook] (/web-ui/node_modules/serverless-webpack/index.js:160:10)
    at BbPromise.reduce (/web-ui/node_modules/web-ui/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/web-ui/node_modules/web-ui/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/web-ui/node_modules/web-ui/lib/classes/PluginManager.js:408:17)
    at ServerlessWebpack.BbPromise.bind.then.then (/web-ui/node_modules/serverless-webpack/index.js:101:51)
From previous event:
    at Object.before:package:createDeploymentArtifacts [as hook] (/web-ui/node_modules/serverless-webpack/index.js:101:10)
    at BbPromise.reduce (/web-ui/node_modules/web-ui/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/web-ui/node_modules/web-ui/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/web-ui/node_modules/web-ui/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/web-ui/node_modules/web-ui/lib/Serverless.js:157:33)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/web-ui/node_modules/web-ui/lib/Serverless.js:144:8)
    at serverless.init.then (/web-ui/node_modules/web-ui/bin/serverless:43:50)

### PR DESCRIPTION
**Pull request by ltetzlaff**
## What did you implement:

Closes #439, #490 

## How did you implement it:

If `.stats` is an Array check for errors in all compilations.
I got errors twice on the way thus used the last output for these.

## How can we verify it:

I use a `webpack.config.ts` extending another `webpack.config.ts`. 

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** HELL YEAH
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by hassankhan** [comment]
Hi @ltetzlaff, thank you so much for your PR 😄! Sorry you had to deal with the ESLint failures, we had an issue where branch protection checks were being bypassed. 

I had a quick look at https://github.com/serverless-heaven/serverless-webpack/pull/509/commits/25db8dedbeccb27d5fa05d5f50df0797739ff0cd which is where you made the actual change, I believe (do let me know if I'm wrong 👍). On the surface, the change seems great - it would be awesome if you could add a few tests checking/verifying the new behaviour, along with an update to the `README.md` describing how users can take advantage of this feature.

**Comment by ltetzlaff** [comment]
> Sorry you had to deal with the ESLint failures, we had an issue where branch protection checks were being bypassed. 

No worries, I guessed there was just something out of place from a previous PR or so ✌️

> add a few tests checking/verifying the new behaviour

Hmm I took a brief look and honestly can't seem to find a good place to insert a test because existing tests seem to throw in intermediate objects of the compilation pipeline. Where do you think should I put an example `webpack.config.ts` and pack from it?

**Comment by RishikeshDarandale** [comment]
@hassankhan , @ltetzlaff , any update on this?

**Comment by RishikeshDarandale** [comment]
@ltetzlaff , Can you please rebase and get ready this one for merge?

@hassankhan , please let us know when can be this included in release.

**Comment by HyperBrain** [comment]
I will have a look

**Comment by RishikeshDarandale** [comment]
@HyperBrain, any luck?

**Comment by HyperBrain** [comment]
@RishikeshDarandale @ltetzlaff Finally, I'm preparing the latest update. Due to the other fixes, there are some conflicts in some of the files now. Can you try to fix them, so that I can get this one in? For the package.json, it should be up to date already in master.

**Comment by ltetzlaff** [comment]
Hi there, sorry for leaving this one barren for so long - will take a look at rebasing it onto master in the next days, feel free to do so before if you need it for the release or so ✌️🔜

**Comment by RishikeshDarandale** [comment]
@ltetzlaff , looks like this change will not work correctly. if `package.individually` is set to `true`, plugin is creating an `multi-compile` option for each individual function.

Thus, according to me if the multi-compile option is provided as below, then `package.individually` should not be allowed/permitted. When multi-compile option is provided, then it;s the responsibility of client to create the package as per one the need.

```
module.exports = [
  {
    entry: ./src/server.js',
    target: 'node',
    externals: [nodeExternals()],
    output: {
      libraryTarget: 'commonjs',
      path: path.join(__dirname, '.webpack'),
      filename: '[name].js'
    },
  },
  {
    entry: './src/client.js',
    target: 'node',
    output: {
      libraryTarget: 'commonjs',
      path: path.join(__dirname, '.webpack'),
      filename: '[name].js'
    },
  },
];
```

@hassankhan / @HyperBrain , let me know your thoughts as well.

I have made [these](https://gist.github.com/RishikeshDarandale/7b12afcb073feb53a11599aae818ac37) changes in `validate.js` for the above one. I have to still verify all permutation and combination if this multi-compile change.

**Comment by RishikeshDarandale** [comment]
@HyperBrain , @hassankhan , @ltetzlaff I have created the new pull request #537 with my understanding. Please verify and let me know your comments!

**Comment by miguel-a-calles-mba** [comment]
Is this PR still needed? Or do we use https://github.com/serverless-heaven/serverless-webpack/pull/537 instead?

**Comment by ltetzlaff** [comment]
I'm closing this in favor of #537, looks better to me ✌️

**Pull request closed without merging**
