### PR TITLE
When using `SLS_DEBUG` env var, more log will be dumped

### PR DESCRIPTION
**Pull request by kennyhyun**
## What did you implement:

Related to #1508 and probably #1653 too

## Todos:

- [x] Write tests
- [ ] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by vicary** [comment]
@kennyhyun What was the errors you are working with?

Depending on the specific error that is sent to `stdout` instead of `stderr`, it could either be
1. An incorrect implementation, or
2. Changing `toString()` in `SpawnError` may be a better option instead.

**Comment by j0k3r** [comment]
@vicary I think it's related to https://github.com/serverless-heaven/serverless-webpack/issues/1508#issuecomment-2126189271

**Comment by kennyhyun** [comment]
yes @vicary thanks

@vicary yeah I tried SpawnError as well but it was not logged.

and `SpawnError` is an exported function, so I could not imagine the consequences.

if it logs errors, and you guys think `SpawnError` is better, I can change

Thanks for the quick response!

**Comment by kennyhyun** [comment]
after reading more, I think npm/yarn packager doesn't log stdout from the SpawnError instance

should I merge stdout into stderr if stderr was empty string or packagers should be updated? I am two minded

**Comment by kennyhyun** [comment]
@vicary one of the errors I was dealing with was,

```
.../@nodert-win10-rs4/windows.storage install$ node-gyp rebuild
../../../../../node_modules/parse-domain postinstall$ run-s build:tries
.../@nodert-win10-rs4/windows.storage install: gyp info it worked if it ends with ok
.../@nodert-win10-rs4/windows.storage install: gyp info using node-gyp@5.1.1
.../@nodert-win10-rs4/windows.storage install: gyp info using node@18.20.2 | linux | x64
.../@nodert-win10-rs4/windows.storage install: gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
.../@nodert-win10-rs4/windows.storage install: (node:103869) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
.../@nodert-win10-rs4/windows.storage install: (Use `node --trace-deprecation ...` to show where the warning was created)
.../@nodert-win10-rs4/windows.storage install: gyp info spawn /usr/bin/python3
.../@nodert-win10-rs4/windows.storage install: gyp info spawn args [
```

which resolved by downgrading python to 3.10

**Comment by kennyhyun** [comment]
Sorry I cannot reproduce that anymore.

Can I just console.log stdout when SLS_DEBUG was specified instead?

**Comment by vicary** [comment]
@j0k3r thanks for referencing to the source!

@kennyhyun It's not easy to generalize a solution at the level of `spawnProcess`. But when we look at `npm.js` and `yarn.js`, it's more safer to do stdout + stderr at the respective `.catch()`. What do you think?

**Comment by kennyhyun** [comment]
@vicary thanks for the feedback.

yeah I agree, let me do that in `npm.js` and `yarn.js`

**Review by vicary — APPROVED** [review]

**Pull request merged**
