### PR TITLE
Merge 5.4.0 into master

### PR DESCRIPTION
**Pull request by j0k3r**
I would like to merge the 5.4.0 branch into master so the master branch will be ready to accept current PR targeting the 5.4.0 milestone and then I'll rebase all PRs.

### CODE REVIEW

**Review by miguel-a-calles-mba — CHANGES_REQUESTED** [review]
Thanks for keeping things moving along, @j0k3r.

Did the change log get updated anywhere?

**Comment by j0k3r** [comment]
I planned to update it later :)

**Comment by miguel-a-calles-mba** [comment]
No worries! I updated the change log file. Let me know whether you agree and we can get this out the door.

**Comment by j0k3r** [comment]
@miguel-a-calles-mba it looks ok 👍

**Review by miguel-a-calles-mba — APPROVED** [review]
Thanks, @j0k3r!

**Pull request merged**
