### PR TITLE
Add support for Yarn network-concurrency option

### LINKED ISSUE #549: Add support for Yarn network-concurrency option
# This is a Feature Proposal

## Description

When running with Yarn as the package manager in CI/CD environments, packing frequently fails due to a known bug in Yarn (see https://github.com/yarnpkg/yarn/issues/2629).  The failure generally shows up something like:

>  yarn install --frozen-lockfile --non-interactive failed with code 1
>  error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/usr/local/share/.cache/yarn/v6/npm-axios-0.19.2-3ea36c5d8818d0d5f8a8a97a6d36b86cdc00cb27-integrity/node_modules/axios/lib'".

Which dependency it fails to install varies from build to build due to the nature of the Yarn bug.  The only known work-around for this is to use the network-concurrency option of Yarn.  So I propose adding the network-concurrency packager option to the list of supported options for Yarn.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.1
* ***Webpack version you're using***: 4.41.0
* ***Serverless Framework Version you're using***: 1.53.0
* ***Operating System***: Amazon Linux
* ***Stack Trace (if available)***:
  Error --------------------------------------------------
 
  yarn install --frozen-lockfile --non-interactive failed with code 1
  error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/usr/local/share/.cache/yarn/v6/npm-axios-0.19.2-3ea36c5d8818d0d5f8a8a97a6d36b86cdc00cb27-integrity/node_modules/axios/lib'".
  
      at ChildProcess.<anonymous> (/codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/utils.js:92:16)
      at ChildProcess.emit (events.js:210:5)
      at ChildProcess.EventEmitter.emit (domain.js:476:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
  From previous event:
      at Object.spawnProcess (/codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/utils.js:73:10)
      at Function.install (/codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/packagers/yarn.js:118:18)
      at /codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/packExternalModules.js:293:33
      at /codebuild/output/src494211422/src/node_modules/universalify/index.js:23:46
  From previous event:
      at /codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/packExternalModules.js:290:16
  From previous event:
      at /codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/packExternalModules.js:227:12
  From previous event:
      at ServerlessWebpack.packExternalModules (/codebuild/output/src494211422/src/node_modules/serverless-webpack/lib/packExternalModules.js:214:8)
  From previous event:
      at Object.webpack:package:packExternalModules [as hook] (/codebuild/output/src494211422/src/node_modules/serverless-webpack/index.js:165:10)
      at /codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:505:55
  From previous event:
      at PluginManager.invoke (/codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:505:22)
      at PluginManager.spawn (/codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:525:17)
      at ServerlessWebpack.<anonymous> (/codebuild/output/src494211422/src/node_modules/serverless-webpack/index.js:102:51)
  From previous event:
      at Object.before:package:createDeploymentArtifacts [as hook] (/codebuild/output/src494211422/src/node_modules/serverless-webpack/index.js:102:10)
      at /codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:505:55
  From previous event:
      at PluginManager.invoke (/codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:505:22)
      at PluginManager.spawn (/codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:525:17)
      at Deploy.<anonymous> (/codebuild/output/src494211422/src/node_modules/serverless/lib/plugins/deploy/deploy.js:115:50)
  From previous event:
      at Object.before:deploy:deploy [as hook] (/codebuild/output/src494211422/src/node_modules/serverless/lib/plugins/deploy/deploy.js:100:30)
      at /codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:505:55
  From previous event:
      at PluginManager.invoke (/codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:505:22)
      at /codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:540:24
  From previous event:
      at PluginManager.run (/codebuild/output/src494211422/src/node_modules/serverless/lib/classes/PluginManager.js:540:8)
      at /codebuild/output/src494211422/src/node_modules/serverless/lib/Serverless.js:115:33
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Serverless.run (/codebuild/output/src494211422/src/node_modules/serverless/lib/Serverless.js:102:74)
      at /codebuild/output/src494211422/src/node_modules/serverless/bin/serverless.js:72:30
      at /codebuild/output/src494211422/src/node_modules/serverless/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:136:16
      at /codebuild/output/src494211422/src/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /codebuild/output/src494211422/src/node_modules/graceful-fs/graceful-fs.js:57:14
      at /codebuild/output/src494211422/src/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqCallback.oncomplete (fs.js:146:23)
  From previous event:
      at /codebuild/output/src494211422/src/node_modules/serverless/bin/serverless.js:72:8
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)
  From previous event:
      at Object.<anonymous> (/codebuild/output/src494211422/src/node_modules/serverless/bin/serverless.js:57:4)
      at Module._compile (internal/modules/cjs/loader.js:956:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
      at Module.load (internal/modules/cjs/loader.js:812:32)
      at Function.Module._load (internal/modules/cjs/loader.js:724:14)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
      at internal/main/run_main_module.js:17:11
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.13.0
     Framework Version:         1.53.0
     Plugin Version:            3.1.1
     SDK Version:               2.1.1
     Components Core Version:   1.1.1
     Components CLI Version:    1.2.3
 
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### PR DESCRIPTION
**Pull request by cfroese**
## What did you implement:

Closes #549

Adds the ability to specify the network-concurrency option when using Yarn as the packager.

## How did you implement it:

Implemented using the existing ignore-scripts option as an example.

## How can we verify it:

Sample config:
``` 
webpack:
  packager: 'yarn'
  packagerOptions:
    networkConcurrency: 1
```

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by cfroese** [comment]
I'm not sure how to complete the last Todo for this PR.  The fork is in an organization and I do not see the "Allow edits from maintainers" option.

**Comment by j0k3r** [comment]
Thanks for the PR @cfroese.
Can you rebase against the master and fix conflicts? 🙏

**Comment by cfroese** [comment]
@j0k3r Thanks for the reminder to update this PR.  It's ready for review again.

**Review by j0k3r — APPROVED** [review]
I'll ship it in 5.5.0, thanks for rebasing! 👐

**Comment by j0k3r** [comment]
Could you rebase again?

**Comment by j0k3r** [comment]
Sorry @cfroese, some stuff got merged since your updated your branch, could you do it again?

**Comment by cfroese** [comment]
@j0k3r No worries.  I'll keep updating until this is merged.  :)

**Comment by j0k3r** [comment]
One last rebase and it'll be ok :)

**Pull request merged**
