### PR TITLE
Fix eslint prettier

### LINKED ISSUE #515: prettier and eslint configs conflict and break tests
# This is a Bug Report

## Description
Prettier has the `bracketSpacing: false` while eslint expects spacing around brackets for example right after committing code if I run eslint again I get these errors:

```
$ npm run eslint

> serverless-webpack@5.3.1 eslint /Users/als/code/serverless-webpack
> node node_modules/eslint/bin/eslint.js --ext .js lib


/Users/als/code/serverless-webpack/lib/packagers/yarn.js
   31:18  error  A space is required after '['   array-bracket-spacing
   31:76  error  A space is required before ']'  array-bracket-spacing
   60:38  error  A space is required after '{'   object-curly-spacing
   60:57  error  A space is required before '}'  object-curly-spacing
  128:18  error  A space is required after '['   array-bracket-spacing
  128:70  error  A space is required before ']'  array-bracket-spacing
  135:46  error  A space is required after '{'   object-curly-spacing
  135:50  error  A space is required before '}'  object-curly-spacing
  146:20  error  A space is required after '['   array-bracket-spacing
  146:38  error  A space is required before ']'  array-bracket-spacing
  148:48  error  A space is required after '{'   object-curly-spacing
  148:52  error  A space is required before '}'  object-curly-spacing

/Users/als/code/serverless-webpack/lib/packagers/yarn.test.js
   50:52  error  A space is required after '{'                   object-curly-spacing
   50:77  error  A space is required before '}'                  object-curly-spacing
   56:1   error  Expected indentation of 8 spaces but found 10   indent
   57:1   error  Expected indentation of 10 spaces but found 12  indent
   58:1   error  Expected indentation of 10 spaces but found 12  indent
   58:13  error  A space is required after '['                   array-bracket-spacing
   58:59  error  A space is required before ']'                  array-bracket-spacing
   59:1   error  Expected indentation of 10 spaces but found 12  indent
   59:13  error  A space is required after '{'                   object-curly-spacing
   59:27  error  A space is required before '}'                  object-curly-spacing
   60:1   error  Expected indentation of 8 spaces but found 10   indent
  113:27  error  A space is required after '{'                   object-curly-spacing
  113:62  error  A space is required before '}'                  object-curly-spacing
  234:27  error  A space is required after '{'                   object-curly-spacing
  234:72  error  A space is required before '}'                  object-curly-spacing
  242:13  error  A space is required after '['                   array-bracket-spacing
  242:65  error  A space is required before ']'                  array-bracket-spacing
  254:27  error  A space is required after '{'                   object-curly-spacing
  254:72  error  A space is required before '}'                  object-curly-spacing
  257:38  error  A space is required after '{'                   object-curly-spacing
  257:58  error  A space is required before '}'                  object-curly-spacing
  303:27  error  A space is required after '{'                   object-curly-spacing
  303:57  error  A space is required before '}'                  object-curly-spacing
  306:41  error  A space is required after '['                   array-bracket-spacing
  306:52  error  A space is required before ']'                  array-bracket-spacing
  312:11  error  A space is required after '['                   array-bracket-spacing
  312:23  error  A space is required before ']'                  array-bracket-spacing
  319:11  error  A space is required after '['                   array-bracket-spacing
  319:23  error  A space is required before ']'                  array-bracket-spacing

/Users/als/code/serverless-webpack/lib/utils.js
  112:17  error  A space is required after '{'   object-curly-spacing
  112:32  error  A space is required before '}'  object-curly-spacing

✖ 43 problems (43 errors, 0 warnings)
  43 errors and 0 warnings potentially fixable with the `--fix` option.
```
Another issue is that `trailingComma: 'all'` breaks tests in node v6 where dangling commas in function arguments is not allowed.

Prettier should be set up as an ESLint rule using https://github.com/prettier/eslint-plugin-prettier this way linting and formatting is done when running `npx eslint --fix`. Another option is https://github.com/prettier/prettier-eslint-cli. 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.1
* ***Webpack version you're using***:4.33.0
* ***Serverless Framework Version you're using***: 1.30.3
* ***Operating System***: OS X 10.13
* ***Stack Trace (if available)***:

### PR DESCRIPTION
**Pull request by asprouse**
## What did you implement:

Closes #515

## How did you implement it:
- Configure [prettier-eslint](https://github.com/prettier/prettier-eslint-cli) to format code, remove eslint-config-prettier 
- Update prettier config to be closer to existing code
- Move `npm test` command out of `lint-staged` to `.huskyrc`. This was causing errors trying to run staged files as if they were tests. All tests should be run not just the staged test files.
- Reformat code with [prettier-eslint](https://github.com/prettier/prettier-eslint-cli)

## How can we verify it:
- @HyperBrain Look at the last commit in this PR and make sure that the code style is acceptable since introducing prettier normalizes spacing, semicolons, line-length, etc. I tried to make the config as close to the current style preferences but the current ESLint rules weren't tight enough to enforce consistency code being reformatted was inevitable.
- run `npm run format` then `npm run eslint` and verify there are no formatting lint issues
- Try committing some code then run `npm run eslint` and ensure there are no issues.

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped (Some existing lines were split that contained uncovered code this increased the number of uncovered lines but didn't affect branches or functions).
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by HyperBrain** [comment]
Looks good to me. Now it should be much easier again to contribute without anyone being annoyed by uncontrollable changes.

**Comment by asprouse** [comment]
Great! Merge away!

**Comment by HyperBrain** [comment]
Will do it this evening.

**Comment by HyperBrain** [comment]
Merged. Feel free to get the other PR to fit now ;-)

**Pull request merged**
