### PR TITLE
Skip compile & packaging if --no-build is set

### LINKED ISSUE #398: Support --no-build for package` and `deploy
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

When using yarn workspaces, it's common for a service to depend on modules that are contained within the workspace.  In a CI/CD process, we would like to execute a test/build step which produces a deployable artifact (e.g. a zip of the service folder) which can be promoted through various environments.  At deploy time, the deployable artifact will not exist within the 'workspaces' structure, so yarn/npm and thus webpack are unable to locate some of the dependencies.

If `serverless deploy` supported a `--no-build` option, then we could do:

1. `serverless webpack`
1. zip folder
1. unzip in prep for deployment to an environment
1. `serverless deploy --no-build -stage qa` - this should package and deploy the serverless service using the existing `.webpack` contents

* If there is additional config how would it look

N/A

Similar or dependent issue(s):
* https://github.com/serverless/serverless/issues/352 - In reality, this proposal is really only useful due to serverless's deployment model - if this serverless issue were completed, then it would make this option unnecessary, as the output of `serverless package` would then be deployable to any given environment.

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.1.5
* ***Webpack version you're using***: 4.8.1
* ***Serverless Framework Version you're using***: 1.27.2
* ***Operating System***: linux
* ***Stack Trace (if available)***: none

### PR DESCRIPTION
**Pull request by jamesmbourne**
## What did you implement:

Closes #398 

Allow the `--no-build` flag to commands that invoke the `before:package:createDeploymentArtifacts` hook. This means that build output can be generated (e.g. in CI environments) and then deployed without having to re-build each time.

## How did you implement it:

Use the existing `build` option to skip the `compile` and `package` steps for the `before:package:createDeploymentArtifacts` hook.

## How can we verify it:

1. Generate build output with `sls webpack`
2. Run `sls deploy --no-build`
3. The existing `.webpack` (or other as specified by `--out`) directory should be used an no Webpack compilation occurs

## Todos:

- [X] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by shredder2500** [comment]
Just tested the code in this PR, everything seems to work as expected from my test. This is a must have feature for us. What is left to do before this can be reviewed?

**Comment by shredder2500** [comment]
I tested this today, everything is working as I would expect. what is left to do before this is ready for review?

**Comment by HyperBrain** [comment]
I will do a review this weekend and I've already tagged the related issue with 5.4.0 :-)

**Comment by hassankhan** [comment]
Hi @jamesmbourne, thanks for the PR 👍 ! Any chance you could add some documentation to the `README.md` as well?

**Comment by jamesmbourne** [comment]
Hey @hassankhan yes I will make sure to update that. 

Testing it locally with a real deployment I have noticed some issues where it seems to bundle `node-modules` in the ZIP when running `serverless deploy --no-build`. 

This appears to call the packaging phase - is there something that will need to be modified within that as well to be aware of the `--no-build flag`?

**Comment by shredder2500** [comment]
any updates on this?

**Comment by jamesmbourne** [comment]
@shredder2500 I've been a bit busy recently but I'll have another look at it and try and get the PR read for review!

**Comment by jamesmbourne** [comment]
@HyperBrain I've done some more digging at it seems like we will need to only skip the `webpack:compile` phase, but continue to run `webpack:package` to actually generate the ZIP containing the bundled JS.

In the `webpack:package` phase, the `stats` object from compilation is used to determine what should be deployed e.g:

```js
const stats = {
  stats: [
    {
      compilation: {
        compiler: {
          outputPath: "/my/Service/Path/.webpack/service"
        }
      }
    }
  ]
};
```

If compile is skipped, we do not have this object to determine what has already been built. Perhaps we can use the information provided by `this.webpackConfig` instead? It contains the path to each built function (as needed here: https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/packageModules.js#L86), although other usages of it (e.g. https://github.com/serverless-heaven/serverless-webpack/blob/master/lib/packExternalModules.js#L156) need access to more in-depth information about the compilation process.

Do you have any thoughts on this?

**Comment by shredder2500** [comment]
popping in again to see if there is any progress. hope yall dont mind. I just need this in order to be able to use this.

**Comment by mrschofield** [comment]
Hi guys,

I'm also just popping in to see where this is at? Is there anything i can do?

**Comment by ctaylor28** [comment]
any updates?

**Comment by jamesmbourne** [comment]
Sorry for the lack of updates on this - I'm currently occupied with other projects and commitments.

The `individually` flag makes this significantly more complex that I otherwise anticipated and may need some additional input to figure out the best approach.

My suggestion would to generate some sort of 'manifest' file after the build phase which includes the necessary information from Webpack but it would be good to hear any other suggestions.

I'll endeavour to pick this back up as it does seem a feature that plenty of people would find useful.

**Comment by ctaylor28** [comment]
is this just waiting on the code coverage check now?

**Comment by ctaylor28** [comment]
is this PR dead?

**Comment by jamesmbourne** [comment]
> is this PR dead?

Sorry @ctaylor28, I've been too busy to be working on this at the moment. I've picked it up again.

I think it just needs some tests putting in for the `save()` method for compile stats to get the coverage up, and then a review.

**Comment by ctaylor28** [comment]
> > is this PR dead?
> 
> Sorry @ctaylor28, I've been too busy to be working on this at the moment. I've picked it up again and will try and get the PR ready for review.
> 
> I think it just needs some tests putting in for the `save()` method for compile stats to get the coverage up, and then a review.

looks like you also have two failing tests

**Comment by jamesmbourne** [comment]
@HyperBrain I think this should be good for review now if you're available to do so.

**Comment by ctaylor28** [comment]
@HyperBrain any chance we can get this reviewed soon?

**Comment by jamesmbourne** [comment]
After having a think about this, we could probably simplify this to avoid the need to serialise the Webpack stats entirely.

1. When `sls webpack` is run, an artifact ZIP is stored in `.serverless`. Modify this to store it in `.webpack` as the `.serverless` directory is deleted by the Serverless framework which is beyond our control.
2. When `sls package` or `sls deploy` is run, copy the artifact archives from the `.webpack` directory to `.serverless` and notify the framework of the location of these artifacts. If `--no-build` is specified, we will skip the generation of these artifacts and use the existing ones contained in `.webpack`.

I will open a new PR with that implementation and close this one.

This approach should be much simpler as we do not need to get involved in `node_modules` packaging etc. as this will all be in the pre-existing artifact.

**Comment by ctaylor28** [comment]
@jamesmbourne have you made another PR or started work on the other way yet?

**Comment by vicary** [comment]
For future lone souls, this is addressed in and superseded by #560.

**Comment by shredder2500** [comment]
@vicary Thank You!

**Pull request closed without merging**
