### PR TITLE
New: Patch for #570

### LINKED ISSUE #299: JavaScript heap out of memory
# This is a Bug Report

## Description

I'm in the process of trying to upgrade `serverless-webpack` version from `2.2.3`, where I do not experience the following issue. Our serverless configuration has `package: invididually: true` set, and about 40 functions. When I try to upgrade to a later version of `serverless-webpack` and run `sls webpack`, the build will run for about a minute and then I get the following error:

```
lambda:daniel.cottone $ npm run build

> expert-api-lambda@0.1.0 build /Users/daniel.cottone/Projects/expert-api/lambda
> sls webpack --stage dev

Serverless: Bundling with Webpack...
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json
ts-loader: Using typescript@2.5.2 and /Users/daniel.cottone/Projects/expert-api/lambda/tsconfig.json

<--- Last few GCs --->

[42611:0x104001600]    55964 ms: Mark-sweep 1405.7 (1508.8) -> 1405.7 (1508.8) MB, 1721.0 / 0.0 ms  allocation failure GC in old space requested
[42611:0x104001600]    57889 ms: Mark-sweep 1405.7 (1508.8) -> 1405.5 (1487.3) MB, 1923.4 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1923 ms) last resort 
[42611:0x104001600]    59801 ms: Mark-sweep 1405.5 (1487.3) -> 1405.4 (1486.8) MB, 1903.6 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x37341f01ba79 <JS Object>
    1: set [native collection.js:~247] [pc=0x29d828934f21](this=0x332730f95301 <a Map with map 0x23d2df14319>,p=0x3dd499abec41 <String[11]: MediaSource>,x=0x2589b9b1c819 <a SymbolObject with map 0x399abfecde11>)
    2: /* anonymous */(aka /* anonymous */) [/Users/daniel.cottone/Projects/expert-api/lambda/node_modules/typescript/lib/typescript.js:~23166] [pc=0x29d828ba5830](this=0x37341f002241 <...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, v8::internal::JSMapIterator, 2>::Rehash(v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/local/bin/node]
 8: v8::internal::Runtime_MapGrow(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0x29d827e840bd
10: 0x29d828934f21
11: 0x29d828ba5830
12: 0x29d827e86bbb
13: 0x29d828f85beb
Abort trap: 6
```

If I change my serverless config to not package individually, `package: individually: false` then this error goes away. I have tested this with version `3.0.0` and the latest, `4.1.0` with the same results. Don't have this issue with `2.2.3`.

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.1.0
* ***Webpack version you're using***: 3.10.0
* ***Serverless Framework Version you're using***: 1.24.0
* ***Operating System***: macOS 10.12.6
* ***Stack Trace (if available)***: see above

### PR DESCRIPTION
**Pull request by corollari**
## What did you implement:
Recently I ran into the problem described in #299 and after testing several possible solutions (see [this issue comment](https://github.com/serverless-heaven/serverless-webpack/issues/299#issuecomment-731618090) for a more detailed rundown of what I tried) I ended up using the fix implemented in #570. However, I ended up having some problems with the watch command used by serverless-offline. This PR implements a patch that fixes those issues and gets it working properly.

Closes #299

## How did you implement it:
I made the script that is responsible for the watch command compatible with the rest of the changes made in the PR. Note that I didn't make the watch command use worker-farm for compilation when watching the changes, as it currently works fine without it.

## How can we verify it:
1. Verify that #570 works fine (this PR depends on it)
2. Setup a new project that uses serverless-offline and try to spin a new local version with this PR's code, it should work fine

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** Yes
***Is it a breaking change?:*** NO for #570, YES for the current package

### CODE REVIEW

**Comment by racedale** [comment]
Just needed to use this by doing `npm install -D serverless-heaven/serverless-webpack#pull/661/head` to get our builds to work. We also use serverless-offline and #570 didn't work when we went to run tests. 

Key thing (mentioned in the issue comment but not here) must remove use of `webpack-node-externals`. Which results in `node_modules` no longer being an included folder for individually packaged lambdas, and rather bundled directly in the js file.  This will make it harder in the future to inspect a build artifact and confirm which version of a dependency is used by a lambda (for security scans, etc)

**Comment by corollari** [comment]
@racedale Thanks for the feedback. I proposed a solution for the problem you mentioned with `webpack-node-externals` [here](https://github.com/soda0289/serverless-webpack/pull/2#issuecomment-736952844), however I currently don't have the bandwith to implement it.

**Comment by pmcavoy89** [comment]
Is there a way we can break down the work in the ToDos you have listed so we can get this hopefully reviewed and merged? My project needs this too.

**Comment by corollari** [comment]
@pmcavoy89 The todo list is just a standard list that came with the PR template, the PR could just be merged as-is.

**Comment by j0k3r** [comment]
Any chance to rebase against master and fix conflicts?

**Comment by corollari** [comment]
@j0k3r sure, I can work on that

**Comment by pmcavoy89** [comment]
@corollari I get that. I was wondering if I could take any of the items in the ToDo list off your plate to help get this merged in, if we need to that list. I know you had mentioned not having a ton of bandwidth.

**Comment by corollari** [comment]
@pmcavoy89 Oh sorry, I didn't understand you. Yeah I'd really appreciate some help with:
- Rebasing against master
- Implementing the use of a `fork` syscall in order to solve the problems we are currently facing with non-dynamic config files
- Adding a flag that toggles the features provided in this PR

**Pull request closed without merging**
