### PR TITLE
Do not run webpack on a single non-node function

### LINKED ISSUE #755: Custom runtime not workig for deployment of single function
# This is a (Bug Report)

## Description

For bug reports:
* What went wrong?
`serverless deploy function -f functionName` always triggers the "serverless-webpack" plugin even when the runtime is not "nodejs".
* What did you expect should have happened?
serverless-webpack should not trigger on non nodejs runtimes (e.g. python)

The issue resides in within "lib/validate.js". The pull request (https://github.com/serverless-heaven/serverless-webpack/pull/579/files) applied the custom runtime only for "serverless deploy" but not for "serverless deploy function -f".

Similar or dependent issue(s):
* #579 

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.4.0
* ***Webpack version you're using***: 4.46.0
* ***Serverless Framework Version you're using***: 2.31.0
* ***Operating System***: Amazon Linux v2
* ***Stack Trace (if available)***:

### PR DESCRIPTION
**Pull request by j0k3r**
Should fix #755

### CODE REVIEW

**Comment by j0k3r** [comment]
@miguel-a-calles-mba can you check that? 🙏

**Review by miguel-a-calles-mba — APPROVED** [review]
Looks good tome.

**Comment by oduncan** [comment]
Is there a way to force webpack to run when running sls deploy function -f myfunctionname? because that's how I was pushing incremental changes "quickly" and testing my graphql server. Or is there a better way to accomplish this.

**Comment by miguel-a-calles-mba** [comment]
@oduncan, you should be able to run `sls package` before running the single function deploy to package the function.

**Pull request merged**
