### PR TITLE
Adds the ability to specify an excludeFiles glob

### LINKED ISSUE #433: Add ability to exclude files from handler lookup
# This is a Feature Proposal

## Description
Please add the ability to exclude certain files from the handler lookup.  This is to get around the extraneous (and possibly error-prone) `WARNING: More than one matching handlers found for 'handler'. Using 'handler.js'` message when there are unit test files in the same directory.

Possible config example:
```
custom:
  webpack:
    excludeFiles: src/**/*.test.[t|j]s
```

Similar or dependent issue(s):
* #405

### PR DESCRIPTION
**Pull request by designfrontier**
## What did you implement:

Closes #433

## How did you implement it:

Fairly trivial, just used the ignore option in glob to exclude files matching the glob.

## How can we verify it:

1. Setup a serverless project with an index.test.js and an index.js that handle a route
2. Start it up and see that you get a warning about duplicate files matching for index
3. Now pull in this PR
4. add the following to your serverless.yml file in the custom > webpack section
`excludeFiles: **/*.test.js`
5. restart serverless
6. see that the warnings are now gone!

## Todos:

- [x] Write tests
- [x] Write documentation
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by designfrontier** [comment]
Looking for suggestions on which section of the documentation notes should be added to...

**Comment by designfrontier** [comment]
Added documentation in the best place that I could find

**Comment by designfrontier** [comment]
@HyperBrain any thoughts on this?

**Comment by Clement134** [comment]
@HyperBrain this issue looks relatively simple to test and could not introduce breaking changes.
It is possible to merge it?

**Comment by designfrontier** [comment]
@serverless-heaven/serverless-webpack-team Would love to have someone other than me sign off on this.

**Comment by rmngrc** [comment]
Would love to get this merged too 👍

**Comment by hassankhan** [comment]
@designfrontier Will try my best to give it a whirl this week and report back 👍

**Comment by hassankhan** [comment]
Had a chance to run it against my project, all the errors are now gone 👍 Thanks @designfrontier!

**Comment by HyperBrain** [comment]
Released with 5.3.0

**Pull request merged**
